<center><a href="https://pypi.org/project/pandas/"> <img src="https://pypi-camo.freetls.fastly.net/705545a847e60d6d4478c76a8146b9000e339c1c/68747470733a2f2f70616e6461732e7079646174612e6f72672f7374617469632f696d672f70616e6461732e737667" alt="Header" style="width: 400px;"/> </a></center>

## Exploring Pandas Library in this notebook

In [10]:
#Before using it Pandas Module should be installed

import pandas as pd

## Importing Datase using Pandas in my Text Editor

In [11]:
data=pd.read_csv("dataset.csv")

In [12]:
#printing head of the data

print(data.head(5))

      id                        title                 genre original_language  \
0    278     The Shawshank Redemption           Drama,Crime                en
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance                hi
2    238                The Godfather           Drama,Crime                en
3    424             Schindler's List     Drama,History,War                en
4    240       The Godfather: Part II           Drama,Crime                en

                                            overview  popularity release_date  \
0  Framed in the 1940s for the double murder of h...      94.075   1994-09-23
1  Raj is a rich, carefree, happy-go-lucky second...      25.408   1995-10-19
2  Spanning the years 1945 to 1955, a chronicle o...      90.585   1972-03-14
3  The true story of how businessman Oskar Schind...      44.761   1993-12-15
4  In the continuing saga of the Corleone crime f...      57.749   1974-12-20

   vote_average  vote_count
0           8.7       21862
1           8.7        3731
2           8.7       16280
3           8.6       12959
4           8.6        9811

## Reading Data in Pandas

In [13]:
#Reading Header

data.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [14]:
#Reading Particular index by name

print(data[['title', 'genre', 'popularity']])  #slicing 0:5

#or you can just do data.title but above is more accurate

                                              title  \
0                          The Shawshank Redemption
1                       Dilwale Dulhania Le Jayenge
2                                     The Godfather
3                                  Schindler's List
4                            The Godfather: Part II
...                                             ...
9995                             The Last Airbender
9996                       Sharknado 3: Oh Hell No!
9997                                Captain America
9998  In the Name of the King: A Dungeon Siege Tale
9999                                         Domino

                                                 genre  popularity
0                                          Drama,Crime      94.075
1                                 Comedy,Drama,Romance      25.408
2                                          Drama,Crime      90.585
3                                    Drama,History,War      44.761
4                                          Drama,Crime      57.749
...                                                ...         ...
9995                          Action,Adventure,Fantasy      98.322
9996  Action,TV Movie,Science Fiction,Comedy,Adventure      12.490
9997                        Action,Science Fiction,War      18.333
9998                    Adventure,Fantasy,Action,Drama      15.159
9999                             Thriller,Action,Crime      16.482

[10000 rows x 3 columns]

In [15]:
#printing one row 

data.iloc[1:3]

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280

In [16]:
#give me details of paticular index like here the "title"

data.iloc[2,1]

'The Godfather'

#iterating
# There aare 10k movies everything will be given here it may crash

for id, title in data.iterrows():
    print(id, row['title'])

In [17]:
#going to specific row or property

data.loc[data['genre']== "Drama"] #restriction only one property at a time

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
10,389,12 Angry Men,Drama,en,The defense and the prosecution have rested an...,31.946,1957-04-10,8.5,6533
32,510,One Flew Over the Cuckoo's Nest,Drama,en,A petty criminal fakes insanity to serve his s...,27.541,1975-05-18,8.4,8703
33,550,Fight Club,Drama,en,A ticking-time-bomb insomniac and a slippery s...,58.676,1999-10-15,8.4,24441
37,255709,Hope,Drama,ko,After 8-year-old So-won narrowly survives a br...,17.189,2013-10-02,8.4,398
43,599,Sunset Boulevard,Drama,en,A hack screenwriter writes a screenplay for a ...,17.814,1950-08-10,8.4,1982
...,...,...,...,...,...,...,...,...,...
9759,14174,Lie with Me,Drama,en,"Happily unattached, the sexually voracious Lei...",27.272,2005-09-10,5.1,205
9844,17680,The Girlfriend Experience,Drama,en,"Chelsea is an in-demand call girl whose $2,000...",9.013,2009-05-22,5.0,235
9876,327040,Bang Gang (A Modern Love Story),Drama,fr,"Biarritz. Sixteen-year-old George, the high sc...",5.260,2015-08-26,4.9,223
9891,328901,The Benefactor,Drama,en,A newly married couple are forced to navigate ...,7.346,2015-04-17,4.9,218
9902,5458,Cruel Intentions 2,Drama,en,After his precocious behavior has gotten him b...,25.216,2000-11-09,4.9,300

# SUMMARY

for acessing dataset Pandas and just -> pd.csv_read("<name.type>")

for printing column -> data.column

for acessing rows -> data.iloc[slicing]

for locating specific object of dataset for -> data.loc

## Sorting Accending/Decending

In [18]:
data.describe()

                  id    popularity  vote_average    vote_count
count   10000.000000  10000.000000  10000.000000  10000.000000
mean   161243.505000     34.697267      6.621150   1547.309400
std    211422.046043    211.684175      0.766231   2648.295789
min         5.000000      0.600000      4.600000    200.000000
25%     10127.750000      9.154750      6.100000    315.000000
50%     30002.500000     13.637500      6.600000    583.500000
75%    310133.500000     25.651250      7.200000   1460.000000
max    934761.000000  10436.917000      8.700000  31917.000000

In [34]:
#sorting

data.sort_values(['id', 'title'], ascending=[1,0]) #firstly ascending and then decending

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,Sum,Total
8858,5,Four Rooms,"Crime,Comedy",en,It's Ted the Bellhop's first night on the job....,12.665,1995-12-09,5.7,2185,17.665,17.665
5167,6,Judgment Night,"Action,Crime,Thriller",en,"While racing to a boxing match, Frank, Mike, J...",8.574,1993-10-15,6.6,247,14.574,14.574
134,11,Star Wars,"Adventure,Action,Science Fiction",en,Princess Leia is captured and held hostage by ...,77.644,1977-05-25,8.2,17480,88.644,88.644
577,12,Finding Nemo,"Animation,Family",en,"Nemo, an adventurous young clownfish, is unexp...",128.733,2003-05-30,7.8,16604,140.733,140.733
20,13,Forrest Gump,"Comedy,Drama,Romance",en,A man with a low IQ has accomplished great thi...,65.175,1994-06-23,8.5,23009,78.175,78.175
...,...,...,...,...,...,...,...,...,...,...,...
5724,920081,Megaboa,"Horror,Action",en,"On a trip to Colombia, a group of college stud...",6.349,2021-11-26,6.5,318,920087.349,920087.349
367,920394,My Father's Violin,"Drama,Music",tr,Through their shared grief and connection to m...,33.154,2022-01-21,8.0,280,920427.154,920427.154
3206,926899,The House,"Animation,Drama,Comedy,Horror,Fantasy",en,"Across different eras, a poor family, an anxio...",248.175,2022-01-14,7.0,676,927147.175,927147.175
7749,928381,Restless,"Action,Thriller,Crime",fr,After going to extremes to cover up an acciden...,200.943,2022-02-25,6.0,272,928581.943,928581.943
4089,934761,A Perfect Pairing,"Comedy,Romance",en,"To land a major client, an LA wine exec travel...",180.507,2022-05-19,6.8,248,934941.507,934941.507

# Making Changes in dataset

In [42]:
data['Total'] = data['id'] + data['popularity']   #making another cloumn  making a total

data=data.drop(columns=['Total']) #deleting another column completeply

In [43]:
data.head(5)

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,Sum
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862,372.075
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731,19429.408
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280,328.585
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959,468.761
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811,297.749

## Saving our Dataset after all changes

data.to_csv('markdown.csv', index=False) #to .csv file

data.to_txt('markdown.txt', index=False, sep='\t')   #for generating .txt file

# Filtering our Dataset

In [61]:
new_data=data.loc[(data['genre']== 'Crime') & (data['original_language']== 'en')]   #and = & or= | we can do conditions like & data['vote' > 6.9]

In [63]:
new_data.reset_index(drop=True, inplace=True)

new_data

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,457799,"Extremely Wicked, Shockingly Evil and Vile",Crime,en,"A chronicle of the crimes of Ted Bundy, from t...",23.521,2019-05-02,7.0,2883
1,511322,The Good Liar,Crime,en,Career con man Roy sets his sights on his late...,16.081,2019-11-08,6.7,877
2,4997,Wonderland,Crime,en,"On the afternoon of July 1, 1981, Los Angeles ...",8.975,2003-10-23,6.1,200

In [ ]:
#selecting particular string inside a object in column

data.loc[~data['title'].str.contains("Good")]  #delete directly by selecting "~"

In [67]:
data.loc[data['title'].str.contains("Th[a-z]*")]   #filtering based on the first 2 letter

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
5,667257,Impossible Things,"Family,Drama",es,"Matilde is a woman who, after the death of her...",14.358,2021-06-17,8.6,255
13,497,The Green Mile,"Fantasy,Drama,Crime",en,A supernatural tale set on death row in a Sout...,69.118,1999-12-10,8.5,14162
...,...,...,...,...,...,...,...,...,...
9972,89899,The Players,Comedy,fr,Eight short films explore the subject of male ...,9.532,2012-02-29,4.7,590
9978,344268,The New Adventures of Aladdin,"Comedy,Adventure",fr,A pair of losers working at department store p...,10.931,2015-10-14,4.7,779
9982,8285,The Spirit,"Action,Comedy,Thriller,Crime,Science Fiction",en,Down these mean streets a man must come. A he...,11.377,2008-12-25,4.7,803
9990,146203,The Last Exorcism Part II,"Horror,Thriller",en,As Nell Sweetzer tries to build a new life aft...,15.757,2013-02-28,4.7,444
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347

# Conditional Changes

In [72]:
data.loc[data['vote_average']== 8.7 , 'vote_average']== 6.9

data

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221

## Aggregate Function (Group By  mean , sum & count

data.groupby(['vote_average']).mean().sort_values(['<row_name>', ascending=True]) #mean ka jaiga me count or sum

## Working with large dataset

for df in pd.read_csv("markdown.csv", chunksize=5):  # iterate 5 set of each time
    print("GAP")
    print(df)